# Generated by Django 3.1.2 on 2020-12-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_received', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=2047)),
                ('detail', models.CharField(max_length=2047)),
                ('used_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', related_query_name='heartbeat', to='licenses.usedsoftwareproduct')),
            ],
        ),
    ]
