# Generated by Django 3.1.2 on 2020-11-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_received', models.DateTimeField()),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licences.licence')),
            ],
        ),
    ]
