# Generated by Django 3.1.2 on 2020-11-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='detail',
            field=models.CharField(default='', max_length=2047),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='message',
            field=models.CharField(default='', max_length=2047),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', related_query_name='heartbeat', to='licences.licence'),
        ),
    ]
