# Generated by Django 3.1.2 on 2021-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='unknown_location',
            field=models.BooleanField(default=False),
        ),
    ]
