# Generated by Django 3.1.2 on 2020-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UsedSoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', related_query_name='used_product', to='customers.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', related_query_name='used_product', to='licences.softwareproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', related_query_name='module', to='licences.softwareproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', related_query_name='licence', to='licences.softwaremodule')),
                ('used_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licences', related_query_name='licence', to='licences.usedsoftwareproduct')),
            ],
        ),
    ]
