# Generated by Django 3.1.2 on 2020-11-24 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedsoftwareproduct',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usedsoftwareproduct',
            name='version',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
