# Generated by Django 3.1.2 on 2020-11-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20201118_1806'),
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='current_software_version',
            new_name='software_version',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='active',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='software',
        ),
        migrations.AddField(
            model_name='licence',
            name='detail',
            field=models.CharField(default='', max_length=2047),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licence',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='location', to='customers.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licence',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
