# Generated by Django 3.1.2 on 2020-11-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_auto_20201118_1806'),
        ('updates', '0002_auto_20201118_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.AddField(
            model_name='softwaremodule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', related_query_name='module', to='licences.softwareproduct'),
        ),
        migrations.AddField(
            model_name='licence',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='softwares', related_query_name='software', to='licences.softwareproduct'),
            preserve_default=False,
        ),
    ]
