# Generated by Django 3.1.2 on 2020-11-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='product',
            field=models.ManyToManyField(related_name='contact_persons', related_query_name='contact_person', to='licences.SoftwareProduct'),
        ),
    ]
