# Generated by Django 3.1.2 on 2020-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licences', '0002_auto_20201118_1806'),
        ('customers', '0002_auto_20201118_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='product',
            field=models.ManyToManyField(related_name='contact_persons', related_query_name='contact_person', to='licences.SoftwareProduct'),
        ),
    ]
