# Generated by Django 3.1.2 on 2020-12-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=16)),
                ('adviser', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsedSoftwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', related_query_name='used_product', to='customers.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_products', related_query_name='used_product', to='licenses.softwareproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', related_query_name='module', to='licenses.softwareproduct')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=2047)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', related_query_name='license', to='licenses.softwaremodule')),
            ],
        ),
        migrations.CreateModel(
            name='LocationLicense',
            fields=[
                ('license_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='licenses.license')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_licenses', related_query_name='location_license', to='customers.location')),
            ],
            bases=('licenses.license',),
        ),
        migrations.CreateModel(
            name='CustomerLicense',
            fields=[
                ('license_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='licenses.license')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_licenses', related_query_name='customer_license', to='customers.customer')),
            ],
            bases=('licenses.license',),
        ),
    ]
