# Generated by Django 3.1.2 on 2020-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20201212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
