# Generated by Django 3.1.2 on 2021-01-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20201215_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='replace_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', related_query_name='license', to='licenses.license'),
        ),
    ]
