# Generated by Django 3.1.2 on 2021-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_license_replace_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlicense',
            name='replace_count',
            field=models.IntegerField(default=0),
        ),
    ]
